name: flutter_video_caching
description: Video caching, can use with video_player package. It supports formats like m3u8 and mp4,
  play and cache videos simultaneously, precache the video before playing.
version: 0.3.0
homepage: https://github.com/windows7lake/flutter_video_caching

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.6
  flutter_hls_parser: ^2.0.1
  http: ^1.3.0
  path: 1.9.1
  path_provider: ^2.1.5
  synchronized: ^3.1.0+1
  logger: ^2.5.0

flutter: